[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "core"
version = "0.1.0"
dependencies = [
    "requests",
]

requires-python = "==3.11.*"

[tool.uv.sources]
sst = { git = "https://github.com/sst/sst.git", subdirectory = "sdk/python", branch = "dev" }
